name: shutters
description: A super simple app to apply filters and make collages from your photos.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  image_picker: ^1.0.4
  image: ^4.1.3
  path_provider: ^2.1.1
  permission_handler: ^11.0.1
  image_gallery_saver_plus: ^4.0.1
  change_app_package_name: ^1.5.0

dev_dependencies:
  flutter_launcher_icons: "^0.14.3"
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/Shutters.png"
